<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcTcx76\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcTcx76/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQcTcx76.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQcTcx76\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQcTcx76\App_KernelDevDebugContainer([
    'container.build_hash' => 'QcTcx76',
    'container.build_id' => '680e4e94',
    'container.build_time' => 1777929470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcTcx76');
