<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'auth_register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/api/auth/register']], [], [], []],
    'order_create' => [[], ['_controller' => 'App\\Controller\\OrderController::create'], [], [['text', '/api/orders']], [], [], []],
    'order_my' => [[], ['_controller' => 'App\\Controller\\OrderController::myOrders'], [], [['text', '/api/orders/my']], [], [], []],
    'review_create' => [[], ['_controller' => 'App\\Controller\\ReviewController::create'], [], [['text', '/api/reviews']], [], [], []],
    'review_by_service' => [['id'], ['_controller' => 'App\\Controller\\ReviewController::byService'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/reviews/service']], [], [], []],
    'services_list' => [[], ['_controller' => 'App\\Controller\\ServiceController::list'], [], [['text', '/api/services']], [], [], []],
    'service_show' => [['id'], ['_controller' => 'App\\Controller\\ServiceController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/services']], [], [], []],
    'service_create' => [[], ['_controller' => 'App\\Controller\\ServiceController::create'], [], [['text', '/api/services']], [], [], []],
    'api_login' => [[], [], [], [['text', '/api/auth/login']], [], [], []],
];
