name: CI MarketHub

on:
  push:
    branches: [ feature/integration-frontend-backend, main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Test Backend Symfony
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, pdo_mysql

      - name: Install dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist --ignore-platform-reqs

      - name: Check routes
        working-directory: backend
        run: php bin/console debug:router

      - name: Check Symfony
        working-directory: backend
        run: php bin/console about

  frontend:
    name: Build Frontend Vue.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build
        working-directory: frontend
        run: npm run build